
spring:
  main:
    # bean当遇到同样名字的时候，是否允许覆盖注册
    allow-bean-definition-overriding: true
  #thymeleaf配置
  thymeleaf:
    cache: false #关闭缓存
    # prefix: classpath:/templates/ #调整页面路径
    encoding: UTF-8
  #yml环境配置
  profiles:
    active: '@profileActive@'
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  redis:
    host: 123.207.146.122
    port: 6379
    password: dc1318533144cg..
    #连接超时
    timeout: 3000
    database: 0
    jedis:
      pool:
        max-active: 10
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #空闲连接
        max-idle: 8
  mail:
    host: smtp.qq.com
    username: 1318533144@qq.com
    password: wsuqgdjhjtdpggji
    default-encoding: UTF-8
    protocol: smtp
    port: 587




# 日志配置
logging:
  level:
    com.timeblog: INFO
    org.springframework: WARN
    org.spring.springboot.dao: debug


# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.timeblog
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*.xml
  # 加载全局的配置文件
  # configLocation: classpath:mapper/mybatis-config.xml

# 首页设置
security:
  indexUrl: /index/toIndexView
  redirectUrl: /web/index/toIndex
  #静态资源，不予拦截 ，以，分割
  staticUrl: /js/**,/css/**,/font-awesome/**,/layui/**,/img/**,/image/**,/images/**,/font/**,/fonts/**,/web/**,/**/*.png",/**/*.jpg,/login/toLoginView
  csrfCloseUrl: /article/uploadImage/**,/web/**


# pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


