# 开发环境配置
server:
  # 服务端口
  port: 8082
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30


spring:
  profiles:
    #yml环境配置
    active: 'prod'



# 日志配置
logging:
  level:
    com.timeblog: INFO
    org.springframework: WARN
    org.spring.springboot.dao: debug




# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi,com.whcm
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  # configLocation: classpath:mapper/mybatis-config.xml

